import React from "react";
import ReactDOM from "react-dom";
import "./styles/base.css";
import "./styles/forms.css";
import "./styles/type.css";
import "./styles/sidebar.css";
import "./styles/links.css";
import "./styles/toggle.css";
import "./styles/main.css";
import "./styles/code.css";
import "./styles/buttons.css";
import "./styles/alert.css";
import "./styles/footer.css";
import App from "./App";
ReactDOM.render(<App />, document.getElementById("root"));
